# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

# Dependencies
install:
  - composer self-update
  - travis_retry composer update --no-interaction --prefer-source --dev $PREFER_LOWEST

script: phpunit

# Cache dependencies
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c7e5d662086972567218
    on_success: change
    on_failure: always
    on_start: false
